spring:
  application:
    name: home

  #  datasource:
  #    url: jdbc:postgresql://localhost:${SQL_PORT}/${DATABASE_NAME}
  #    username: ${USERNAME}
  #    password: ${PASSWORD}
  #    driver-class-name: org.postgresql.Driver
  #
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # H2 콘솔 확인용 (웹에서 접속: /h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console  # 브라우저에서 localhost:8080/h2-console 접속

  # (선택) H2 DB 경로 지정
  # h2를 연결할 경우 URL만 바꿔서 사용하면 됨
  # spring.datasource.url: jdbc:h2:mem:testdb
#  spring:
#    datasource:
#      url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
